
[build]
  publish = "dist/public"
  command = "npm run build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
